Sistema/Models/Apps/Master/AplicativosView.cs
using Sistema.Assets.DB;
using Sistema.Assets.Entities;
using Sistema.Assets.Functions;
using System.Collections.Generic;
using System.Web;

namespace Sistema.Models
{
    public class AplicativosView
    {
        public int id { get; set; }
        public int id2 { get; set; }
        public Aplicativos aplicativo { get; set; }

        public AplicativosView(int id = 0, int id2 = 0)
        {
            // Identifcadores
            this.id = id;
            this.id2 = id2;

            // Busca registro principal
            this.aplicativo = new AplicativosDB().Buscar(id);

            // Grava o nome do identifcador principal
            HttpContext.Current.Session["ident_name"] = aplicativo.txaplicativo.value;
            HttpContext.Current.Session["ident_code"] = aplicativo.idaplicativo.value;
        }
    }
}

Sistema/Controllers/Apps/Master/AplicativosController.cs
/*
Descrição: Controlador para cadastro de aplicativos
Data: 01/01/2021 - v.1.0
*/

using Functions;
using Sistema.Assets.DB;
using Sistema.Assets.Entities;
using Sistema.Models;
using System;
using System.Web.Helpers;
using System.Web.Mvc;
using System.Web.Routing;

namespace Sistema.Controllers
{
    public class AplicativosController : Controller
    {
        // Dashboard
        [Autentication]
        public ActionResult Dashboard()
        {
            return PartialView("~/Views/Apps/Master/Aplicativos/Dashboard.cshtml");
        }

        // Cadastro
        [Autentication]
        public ActionResult Incluir(int id = 0, int id2 = 0, string register = "")
        {
            // Validação para seleção de registro inicial caso esteja configurado para não exibir a dashboard
            if (register != "")
            {
                id = new AplicativosDB().Paginar(id, register);
            }

            return PartialView("~/Views/Apps/Master/Aplicativos/Incluir.cshtml", new AplicativosView(id, id2));
        }

        // Excluir
        [Autentication]
        public JsonResult Excluir(int id = 0, int id2 = 0)
        {
            Retorno result = new Retorno();

            // Verifica se foi passado id
            if (id > 0)
            {
                Aplicativos aplicativo = new AplicativosDB().Buscar(id);

                // Verifica se encontrou o registro
                if (aplicativo.idaplicativo.value > 0)
                {
                    // Exclusão
                    aplicativo.Excluir();
                    result.success = 1;
                }

                // Identificador não encontrado
                else
                {
                    result.msg = Language.XmlLang(210, 2).Text;
                }
            }

            // Identificador não informado
            else
            {
                result.msg = Language.XmlLang(200, 2).Text;
            }
            return Json(result);
        }

        // Filtro
        [Autentication]
        public ActionResult Filtro()
        {
            return PartialView("~/Views/Apps/Master/Aplicativos/Filtro.cshtml");
        }

        // Gravar
        [Autentication]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult Gravar(FormCollection form)
        {
            Retorno result = new Retorno();

            // Recupera variáveis
            int ident = Convert.ToInt32(Utils.Null(Convert.ToString(Utils.Numbers(form["app_temp_id"])), "0"));
            string aplicativo = Utils.ClearText(form["frm_aplicativo"], 100);
            string action = Utils.ClearText(form["frm_action"], 20);
            string controller = Utils.ClearText(form["frm_controller"], 20);
            int tabela = Convert.ToInt32(Utils.Null(form["frm_idtabela"], "0"));

            // Verifica permissões

            // Valida dados obrigatórios
            if (aplicativo == "")
            {
                result.msg = Language.XmlLang(230, 2).Text + " " + Language.XmlLang(234, 0).Text;
                return Json(result);
            }
            if (action == "")
            {
                result.msg = Language.XmlLang(231, 2).Text + " " + Language.XmlLang(234, 0).Text;
                return Json(result);
            }
            if (controller == "")
            {
                result.msg = Language.XmlLang(232, 2).Text + " " + Language.XmlLang(234, 0).Text;
                return Json(result);
            }

            // Busca registro para gravar
            Aplicativos reg = new AplicativosDB().Buscar(ident);

            // Carrega valores
            reg.txaplicativo.value = aplicativo;
            reg.txaction.value = action;
            reg.txcontroller.value = controller;
            reg.idtabela.value = tabela;

            // Gravar/Alterar
            if (reg.idaplicativo.value == 0)
            {
                // Gravar
                int i = reg.Gravar();
                result.success = 1;
                result.msg = Language.XmlLang(213, 2).Text;
                result.ident = i;
            }
            else
            {
                // Alterar
                reg.Alterar(new AplicativosDB().Buscar(ident));
                result.success = 1;
                result.msg = Language.XmlLang(214, 2).Text;
                result.ident = ident;
            }

            return Json(result);
        }

        // Listagem
        [Autentication]
        [HttpPost]
        public ActionResult ListarWidget(FormCollection form)
        {
            dynamic result = new AplicativosDB().ListarWidget(form);
            return PartialView("~/Views/Widgets/List.cshtml", new WidgetsView_List(new Widgets().Create(form), "", result));
        }


        // Paginação
        [Autentication]
        public int Paginar(int id = 0, int id2 = 0, string action = "")
        {
            return new AplicativosDB().Paginar(id, action);
        }
    }
}

Sistema/Controllers/Apps/Master/MenusController.cs
/*
Descrição: Controlador para cadastro de menus
Data: 01/01/2021 - v.1.0
*/

using Functions;
using Sistema.Assets.DB;
using Sistema.Assets.Entities;
using Sistema.Models;
using System;
using System.Web.Mvc;
using System.Web.Routing;

namespace Sistema.Controllers
{
    public class MenusController : Controller
    {
        // Dashboard
        [Autentication]
        public ActionResult Dashboard()
        {
            return PartialView("~/Views/Apps/Master/Menus/Dashboard.cshtml");
        }

        // Cadastro
        [Autentication]
        public ActionResult Incluir(int id = 0, int id2 = 0, string register = "")
        {
            // Validação para seleção de registro inicial caso esteja configurado para não exibir a dashboard
            if (register != "")
            {
                id = new MenusDB().Paginar(id, register);
            }

            return PartialView("~/Views/Apps/Master/Menus/Incluir.cshtml", new MenusView(id, id2));
        }

        // Excluir
        [Autentication]
        public JsonResult Excluir(int id = 0, int id2 = 0)
        {
            Retorno result = new Retorno();

            // Verifica se foi passado id
            if (id > 0)
            {
                Menus menu = new MenusDB().Buscar(id);

                // Verifica se encontrou o registro
                if (menu.idmenu.value > 0)
                {
                    // Exclusão
                    menu.Excluir();
                    result.success = 1;
                }

                // Identificador não encontrado
                else
                {
                    result.msg = Language.XmlLang(210, 2).Text;
                }
            }

            // Identificador não informado
            else
            {
                result.msg = Language.XmlLang(200, 2).Text;
            }
            return Json(result);
        }

        // Filtro
        [Autentication]
        public ActionResult Filtro()
        {
            return PartialView("~/Views/Apps/Master/Menus/Filtro.cshtml");
        }

        // Gravar
        [Autentication]
        [ValidateInput(false)]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult Gravar(FormCollection form)
        {
            Retorno result = new Retorno();

            // Recupera variáveis
            int ident = Convert.ToInt32(Utils.Null(Convert.ToString(Utils.Numbers(form["app_temp_id"])), "0"));
            int codigo_idioma = Convert.ToInt32(Utils.Null(form["frm_codigo_idioma"], "0"));
            int menu_pai = Convert.ToInt32(Utils.Null(form["frm_idmenu_pai"], "0"));
            int aplicativo = Convert.ToInt32(Utils.Null(form["frm_idaplicativo"], "0"));
            int ordem = Convert.ToInt32(Utils.Null(form["frm_ordem"], "0"));
            string icone = Convert.ToString(form["frm_icone"]).Trim();
            int ativo = Convert.ToInt32(Utils.Null(Convert.ToString(Utils.Null(Utils.Null(form["frm_ativo"]), "0")), "0"));
            int master = Convert.ToInt32(Utils.Null(Convert.ToString(Utils.Null(Utils.Null(form["frm_master"]), "0")), "0"));

            // Verifica permissões

            // Valida dados obrigatórios
            if (codigo_idioma == 0)
            {
                result.msg = Language.XmlLang(28, 2).Text + " " + Language.XmlLang(234, 0).Text;
                return Json(result);
            }  
            if (ordem == 0)
            {
                result.msg = Language.XmlLang(246, 2).Text + " " + Language.XmlLang(234, 0).Text;
                return Json(result);
            }

            // Busca registro para gravar
            Menus menu = new MenusDB().Buscar(ident);

            // Carrega valores
            menu.idmenupai.value = menu_pai;
            menu.idaplicativo.value = aplicativo;
            menu.idcodigoidioma.value = codigo_idioma;
            menu.nrordem.value = ordem;
            menu.txicone.value = icone;
            menu.flativo.value = ativo;
            menu.flmaster.value = master;

            // Gravar/Alterar
            if (menu.idmenu.value == 0)
            {
                // Gravar
                int i = menu.Gravar();
                result.success = 1;
                result.msg = Language.XmlLang(213, 2).Text;
                result.ident = i;
            }
            else
            {
                // Alterar
                menu.Alterar(new MenusDB().Buscar(ident));
                result.success = 1;
                result.msg = Language.XmlLang(214, 2).Text;
                result.ident = ident;
            }

            return Json(result);
        }

        // Listagem
        [Autentication]
        [HttpPost]
        public ActionResult ListarWidget(FormCollection form)
        {
            dynamic result = new MenusDB().ListarWidget(form);
            return PartialView("~/Views/Widgets/List.cshtml", new WidgetsView_List(new Widgets().Create(form), "", result));
        }

        // Paginação
        [Autentication]
        public int Paginar(int id = 0, int id2 = 0, string action = "")
        {
            return new MenusDB().Paginar(id, action);
        }
    }
}

Sistema/Controllers/Apps/Master/ModulosSistemaController.cs
/*
Descrição: Controlador para cadastro de módulos do sistema
Data: 01/01/2021 - v.1.0
*/

using Functions;
using Sistema.Models;
using System.Web.Mvc;
using System.Web.Routing;

namespace Sistema.Controllers
{
    public class ModulosSistemaController : Controller
    {
        // Dashboard
        [Autentication]
        public ActionResult Dashboard()
        {
            return PartialView("~/Views/Apps/Master/Modulos/Dashboard.cshtml");
        }
    }
}

Sistema/Controllers/Apps/Master/TabelasController.cs
/*
Descrição: Controlador para cadastro de tabelas
Data: 01/01/2021 - v.1.0
*/

using Functions;
using Sistema.Assets.DB;
using Sistema.Assets.Entities;
using Sistema.Models;
using System;
using System.Web.Mvc;
using System.Web.Routing;

namespace Sistema.Controllers
{
    public class TabelasController : Controller
    {
        // Dashboard
        [Autentication]
        public ActionResult Dashboard()
        {
            return PartialView("~/Views/Apps/Master/Tabelas/Dashboard.cshtml");
        }

        // Cadastro
        [Autentication]
        public ActionResult Incluir(int id = 0, int id2 = 0, string register = "")
        {
            // Validação para seleção de registro inicial caso esteja configurado para não exibir a dashboard
            if (register != "")
            {
                id = new TabelasDB().Paginar(id, register);
            }

            return PartialView("~/Views/Apps/Master/Tabelas/Incluir.cshtml", new TabelasView(id, id2));
        }

        // Excluir
        [Autentication]
        public JsonResult Excluir(int id = 0, int id2 = 0)
        {
            Retorno result = new Retorno();
            
            // Verifica se foi passado id
            if (id > 0)
            {
                Tabelas tabela = new TabelasDB().Buscar(id);

                // Verifica se encontrou o registro
                if (tabela.idtabela.value > 0)
                {
                    // Exclusão
                    tabela.Excluir();
                    result.success = 1;
                }

                // Identificador não encontrado
                else
                {
                    result.msg = Language.XmlLang(210, 2).Text;
                }
            }

            // Identificador não informado
            else
            {
                result.msg = Language.XmlLang(200, 2).Text;
            }
            return Json(result);
        }

        // Filtro
        [Autentication]
        public ActionResult Filtro()
        {
            return PartialView("~/Views/Apps/Master/Tabelas/Filtro.cshtml");
        }

        // Gravar
        [Autentication]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult Gravar(FormCollection form)
        {
            Retorno result = new Retorno();

            // Recupera variáveis
            int ident = Convert.ToInt32(Utils.Null(Convert.ToString(Utils.Numbers(form["app_temp_id"])), "0"));
            string tabela = Utils.ClearText(form["frm_tabela"], 200);
            int auditoria = Convert.ToInt32(Utils.Null(Convert.ToString(Utils.Null(Utils.Null(form["frm_auditoria"]),"0")), "0")); 
            int codigo_idioma = Convert.ToInt32(Utils.Null(form["frm_codigo_idioma"], "0"));

            // Verifica permissões

            // Valida dados obrigatórios
            if (tabela == "") {
                result.msg = Language.XmlLang(138, 2).Text + " " + Language.XmlLang(234, 0).Text;
                return Json(result);
            }

            // Busca registro para gravar
            Tabelas reg = new TabelasDB().Buscar(ident);

            // Carrega valores
            reg.txtabela.value = tabela;
            reg.idcodigoidioma.value = codigo_idioma;
            reg.flauditoria.value = auditoria;

            // Gravar/Alterar
            if (reg.idtabela.value == 0)
            {
                // Gravar
                int i = reg.Gravar();
                result.success = 1;
                result.msg = Language.XmlLang(213, 2).Text;
                result.ident = i;
            }
            else
            {                
                // Alterar
                reg.Alterar(new TabelasDB().Buscar(ident));
                result.success = 1;
                result.msg = Language.XmlLang(214, 2).Text;
                result.ident = ident;
            }

            return Json(result);
        }

        // Listagem
        [Autentication]
        [HttpPost]
        public ActionResult ListarWidget(FormCollection form)
        {
            dynamic result = new TabelasDB().ListarWidget(form);
            return PartialView("~/Views/Widgets/List.cshtml", new WidgetsView_List(new Widgets().Create(form), "", result));
        }

        // Paginação
        [Autentication]
        public int Paginar(int id = 0, int id2 = 0, string action = "")
        {
            return new TabelasDB().Paginar(id, action);
        }
    }
}

Sistema/Controllers/WidgetsController.cs
using Functions;
using Sistema.Assets.DB;
using Sistema.Assets.Entities;
using Sistema.Models;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Web.Mvc;

namespace Sistema.Controllers
{
    public class WidgetsController : Controller
    {
        // Opções
        [Autentication]
        public ActionResult Options(string id = "")
        {
            return PartialView(new WidgetsView_Options(id));
        }

        // Novo Registro
        [Autentication]
        public ActionResult New(Widgets widget, string texto = "")
        {
            return PartialView(new WidgetsView_New(widget, texto));
        }

        // Listagem
        [Autentication]
        public ActionResult List(Widgets widget, string texto, dynamic result)
        {           
            return PartialView(new WidgetsView_List(widget, texto, result));
        }
    }
}

Sistema/Views/Apps/Master/Tabelas/Dashboard.cshtml
@*
    Descrição: Dashboard do cadastro de tabelas do sistema
    Data: 01/01/2021 - v.1.0
*@

@using Sistema.Assets.DB;
@using Sistema.Assets.Entities;
@using Functions;

<div class="grid-stack">

    @* Novo registro *@
    @Html.Action("New",
        "Widgets",
        new { widget = new Widgets(9, 0, 3, 2, 0, 0, true, "Tabelas", "Incluir", "wdg_new"),
        texto = Language.XmlLang(157, 2).Text })

    @* Listagem *@
    @Html.Action("List",
        "Widgets",
        new { widget = new Widgets(0, 0, 9, 8, 0, 0, false, "Tabelas", "ListarWidget", "wdg_list"),
        texto = Language.XmlLang(162, 2).Text,
        result = new TabelasDB().ListarWidget(null) })

</div>

Sistema/Views/Apps/Master/Tabelas/Filtro.cshtml
@*
    Descrição: Dashboard do cadastro de tabelas do sistema
    Data: 01/01/2021 - v.1.0
*@

@using Functions;

<div class="row">
    <div class="col-sm-6 col-md-6 col-lg-6 col-xl-6">
        @{
            Inputs inp = new Inputs();
            inp.inputType = "text";
            inp.label = Language.XmlLang(138, 2).Text;
            inp.className = "form-control mb-0";
            inp.id = "filter_txtabela";
            inp.maxLenght = 50;
            @Html.Raw(inp.CreateInput());
        }
    </div>
</div>

Sistema/Views/Apps/Master/Tabelas/Incluir.cshtml
@*
    Descrição: Cadastro de tabelas do sistema
    Data: 01/01/2021 - v.1.0
*@

@* Controles do aplicativo *@
@model Sistema.Models.TabelasView

@* Funções *@
@using Functions;

@* Inputs *@
@{ Inputs inp = new Inputs(); }

<div class="row">
    <div class="col-sm-6 col-md-6 col-lg-6 col-xs-12">
        @{
            // Verifica se esta editando algum registro
            if (Model.tabela.idtabela.value > 0)
            {
                inp.inputType = "text";
                inp.label = Language.XmlLang(138, 2).Text;
                inp.id = "frm_tabela";
                inp.className = "form-control bg-readonly";
                inp.required = true;
                inp.validation = "required,minsize=2,maxsize=200";
                inp.readOnly = true;
                inp.inputValue = Model.tabela.txtabela.value;
                @Html.Raw(inp.CreateInput());
            }
            else
            {
                // Verifica se existe alguma tabela que não foi cadastrada
                if (Model.tabelaN.Count > 0)
                {

                    inp.inputType = "select";
                    inp.label = Language.XmlLang(138, 2).Text;
                    inp.id = "frm_tabela";
                    inp.className = "form-control";
                    inp.required = true;
                    inp.validation = "required";
                    inp.options = Model.tabelaN;
                    inp.optionsFields = "ident,text";
                    inp.firstOption = Language.XmlLang(146, 2).Text;
                    inp.inputValue = Model.tabela.txtabela.value;
                    @Html.Raw(inp.CreateInput());
                }
                else
                {
                    inp.inputType = "text";
                    inp.label = Language.XmlLang(138, 2).Text;
                    inp.id = "frm_tabela";
                    inp.className = "form-control";
                    inp.required = true;
                    inp.validation = "required,minsize=2,maxsize=200";
                    inp.readOnly = true;
                    inp.inputValue = "";
                    inp.placeholder = Language.XmlLang(202, 2).Text;
                    @Html.Raw(inp.CreateInput());
                }
            }
        }
    </div>
</div>
<div class="row">
    <div class="col-sm-3 col-md-3 col-lg-3 col-xs-6">
        @{
            // Código do idioma
            inp.inputType = "text";
            inp.label = Language.XmlLang(249, 2).Text;
            inp.id = "frm_codigo_idioma";
            inp.className = "form-control";
            inp.required = true;
            inp.validation = "required,numbers,minsize=1,maxsize=5";
            inp.inputValue = Convert.ToString(Model.tabela.idcodigoidioma.value);
            inp.maxLenght = 10;
            inp.mask = "00000";
            inp.blur = "loadTextLanguage(this.value)";
            @Html.Raw(inp.CreateInput());
        }
    </div>
    <div class="col-sm-3 col-md-3 col-lg-3 col-xs-6">
        <div class="form-group">
            <label for="texto_idioma">@Language.XmlLang(140, 2).Text</label>
            <h4 id="texto_idioma" class="ft-red pt-3">@Language.XmlLang(Convert.ToInt32(Model.tabela.idcodigoidioma.value), 2).Text</h4>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-sm-6 col-md-6 col-lg-6 col-xs-12">
        @{
            // Possui auditoria
            inp.inputType = "switch";
            inp.label = Language.XmlLang(141, 2).Text;
            inp.id = "frm_auditoria";
            inp.inputChecked = (Model.tabela.flauditoria.value == 1 ? true : false);
            @Html.Raw(inp.CreateInput());
        }
    </div>
</div>

<script src="~/Assets/Js/Apps/Master/Tabelas/incluir.js"></script>