Sistema/Controllers/PartialsController.cs
/*
Descrição: Controlador de includes internos do sistema
Data: 01/01/2021 - v.1.0
*/

using Sistema.Assets.DB;
using Sistema.Models;
using System;
using System.Globalization;
using System.Web.Mvc;
using Functions;
using Sistema.Assets.Entities;
using Sistema.Assets.Functions;

namespace Sistema.Controllers
{
    public class PartialsController : Controller
    {
        // Cabeçalho para mobile
        [Autentication]
        public ActionResult HeaderMobile()
        {
            return PartialView();
        }

        // Cabeçalho
        [Autentication]
        public ActionResult Header()
        {
            return PartialView();
        }

        // Menu
        [Autentication]
        public ActionResult Menu()
        {
            return PartialView(new PartialsView_MenuView());
        }

        // Aplicativo
        [Autentication]
        public ActionResult App(string controller = "", string action = "", int id = 0, int id2 = 0)
        {
            // Verifica se foi passado controller e action
            if ((controller != "") && (action != ""))
            {
                // Grava a pagina atual na session para utilizar caso seja feito refresh da página
                Session["current_page"] = controller + "|" + action + "|" + id + "|" + id2;

                // Redireciona para app
                return PartialView(new PartialsView_AppView(controller, action, id, id2));

            }
            // Redireciona para dashboard principal
            else
            {
                return PartialView(new PartialsView_AppView("Home", "Dashboard", id, id2));
            }
        }

        // Dashboard
        [Autentication]
        public JsonResult SaveConfigDashboard(string action = "", string controller = "", int dashboard = 1, string register = "")
        {
            // Retorno
            Retorno result = new Retorno();
            result.msg = Language.XmlLang(208, 2).Text;

            // Busca o código do aplicativo
            int idaplicativo = new AplicativosDB().BuscarActionController(action, controller).idaplicativo.value;

            // Usuário
            int idusuario = Convert.ToInt32(Utils.Null(Convert.ToString(Session["usuario"]), "0"));

            // Busca o registro de configuração da dashboard para o usuário
            Usuarios_Dashboard ud = new Usuarios_DashboardDB().Buscar(idusuario, idaplicativo);

            // Gravar
            if (ud == null)
            {
                Usuarios_Dashboard dash = new Usuarios_Dashboard();
                dash.idusuario.value = idusuario;
                dash.idaplicativo.value = idaplicativo;
                dash.fldashboard.value = dashboard;
                dash.fltiporeg.value = register;
                dash.Gravar();
                result.success = 1;
                result.msg = Language.XmlLang(243, 2).Text;
            }

            // Alterar
            else
            {
                ud.fldashboard.value = dashboard;
                ud.fltiporeg.value = register;
                ud.Alterar();
                result.success = 1;
                result.msg = Language.XmlLang(243, 2).Text;
            }

            // Retorno
            return Json(result);
        }

        // Rodapé
        [Autentication]
        public ActionResult Footer()
        {
            return PartialView();
        }

        // Calculadora
        [Autentication]
        public ActionResult Calculator()
        {
            return PartialView();
        }

        // ***************** CEP *****************

        // Pesquisa CEP
        [Autentication]
        public ActionResult Cep()
        {
            return PartialView();
        }

        // ***************** CHAT *****************

        // Icone
        [Autentication]
        public ActionResult Chat()
        {
            return PartialView();
        }

        // Painel do chat
        [Autentication]
        public ActionResult ChatPanel()
        {
            return PartialView(new PartialsView_ChatPanel());
        }

        // Tela de mensagem do chat
        [Autentication]
        public ActionResult ChatMsg()
        {
            return PartialView();
        }

        // Lista de usuários do chat
        [Autentication]
        public ActionResult ChatPanelList(int online = 1, int offline = 0, string search = "")
        {
            return PartialView(new PartialsView_ChatPanelList(online, offline, search));
        }

        // Grava o novo status de chat do usuário
        [Autentication]
        public void ChatPanelChangeStatus(int status = 0)
        {
            new Usuarios_SistemaDB().AlterarStatusChat(status);
        }

        // Grava a nova configuração de privacidade
        [Autentication]
        public void ChatPanelChangePrivacy(int privacy = 0)
        {
            new Usuarios_SistemaDB().AlterarPrivacidadeChat(privacy);
        }

        // Grava a nova configuração de mensagem
        [Autentication]
        public void ChatPanelChatMsg(int config = 0)
        {
            new Usuarios_SistemaDB().AlterarConfigMsgChat(config);
        }

        // Lista as mensagens
        [Autentication]
        public ActionResult ChatPanelListMsgs(int id = 0)
        {
            return PartialView(new PartialsView_ChatPanelListMsgs(id));
        }

        // ***************** E-MAIL *****************

        [Autentication]
        public ActionResult Email()
        {
            return PartialView();
        }

        [Autentication]
        public ActionResult Whatsapp()
        {
            return PartialView();
        }

        [Autentication]
        public ActionResult ScrollTop()
        {
            return PartialView();
        }

        [Autentication]
        public ActionResult Search()
        {
            return PartialView();
        }

        [Autentication]
        public ActionResult Notifications()
        {
            return PartialView();
        }

        [Autentication]
        public ActionResult QuickActions()
        {
            return PartialView();
        }        

        // Lista de idiomas do sistema
        [Autentication]
        public ActionResult Languages()
        {
            return PartialView();
        }

        // Menu de ações do usuário
        [Autentication]
        public ActionResult UserPanel()
        {
            return PartialView();
        }

        // Retorna a hora atual do servidor
        [Autentication]
        public string Clock()
        {
            CultureInfo culture = new CultureInfo("pt-BR");
            DateTimeFormatInfo dtfi = culture.DateTimeFormat;

            int day = DateTime.Now.Day;
            int year = DateTime.Now.Year;
            string month = culture.TextInfo.ToTitleCase(dtfi.GetMonthName(DateTime.Now.Month));
            string weekday = culture.TextInfo.ToTitleCase(dtfi.GetDayName(DateTime.Now.DayOfWeek));
            string date = weekday + ", " + day + " " + Language.XmlLang(5, 0).Text + " " + month + " " + Language.XmlLang(5, 0).Text + " " + year + "<br>" + DateTime.Now.ToString("HH:mm:ss");
            return date;
        }

    }
}

Sistema/Views/Shared/_Layout.cshtml
@*
Descrição: Página inicial do sistema, definição do layout
Data: 01/01/2021 - v.1.0
*@

@using Functions;

<!DOCTYPE html>

<html lang="pt-br">

    @* Head *@
    <head>
        <meta charset="utf-8" />
        <title>@Language.XmlLang(1, 1).Text</title>
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />

        @* Fonts *@
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700|Roboto:300,400,500,600,700" />

        @* Styles *@
        @Styles.Render("~/system_css")

        @* Icon *@
        <link rel="shortcut icon" href="assets/media/logos/favicon.ico" />
    </head>

    @* Body *@
    <body class="kt-quick-panel--right kt-demo-panel--right kt-offcanvas-panel--right kt-header--fixed kt-header-mobile--fixed kt-subheader--enabled kt-subheader--fixed kt-subheader--solid kt-aside--enabled kt-aside--static kt-aside--minimize kt-footer--fixed kt-page--loading">
        
        @* Header Mobile *@
        @Html.Action("HeaderMobile", "Partials")

        <div class="kt-grid kt-grid--hor kt-grid--root">

            <div class="kt-grid__item kt-grid__item--fluid kt-grid kt-grid--ver kt-page">

                @* Menu *@
                @Html.Action("Menu", "Partials")

                <div class="kt-grid__item kt-grid__item--fluid kt-grid kt-grid--hor kt-wrapper" id="kt_wrapper">

                    @* Header *@
                    @Html.Action("Header", "Partials")

                    <div class="kt-content  kt-grid__item kt-grid__item--fluid kt-grid kt-grid--hor" id="kt_content">

                        @* Objeto usado para corrigir a posição das opções dentro dos portlets *@
                        <label id="temp_portlet_dropdown" style="position:absolute; z-index:999">
                            <div class="dropdown-menu dropdown-menu-right"></div>
                        </label>

                        @* Content *@
                        <div class="kt-container kt-container--fluid  kt-grid__item kt-grid__item--fluid" id="kt_content_app">
                            @RenderBody()
                        </div>

                    </div>

                    @* Footer *@
                    @Html.Action("Footer", "Partials")
                </div>
            </div>
        </div>

        @* Chat Panel *@
        @Html.Action("ChatPanel", "Partials")

        @* Tela de mensagem do chat *@
        @Html.Action("ChatMsg", "Partials")

        @* Scroll Top *@
        @Html.Action("ScrollTop", "Partials")

    </body>

</html>

@* Scripts *@
@Scripts.Render("~/system_scripts")
@Scripts.Render("~/system_timer")
@Scripts.Render("~/system_header")
@Scripts.Render("~/system_footer")
@RenderSection("scripts", required: false)